
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffData : Luban.BeanBase
{
    public BuffData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["costEvent"].IsNumber) { throw new SerializationException(); }  CostEvent = (EventType)_buf["costEvent"].AsInt; }
        { if(!_buf["isStackable"].IsBoolean) { throw new SerializationException(); }  IsStackable = _buf["isStackable"]; }
    }

    public static BuffData DeserializeBuffData(JSONNode _buf)
    {
        return new BuffData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly EventType CostEvent;
    public readonly bool IsStackable;
   
    public const int __ID__ = -1458391363;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "costEvent:" + CostEvent + ","
        + "isStackable:" + IsStackable + ","
        + "}";
    }
}
}

