
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum CardTargetType
    {
        无 = 0,
        食材 = 1,
        周围有空位的食材 = 2,
        周围有食材的食材 = 3,
        任意格子 = 4,
    }

} 

