
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Condition_位于首尾 : Condition
{
    public Condition_位于首尾(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
    }

    public static Condition_位于首尾 DeserializeCondition_位于首尾(JSONNode _buf)
    {
        return new Condition_位于首尾(_buf);
    }

    public readonly int Type;
   
    public const int __ID__ = -770884915;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "}";
    }
}
}

