
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Condition_DV检测 : Condition
{
    public Condition_DV检测(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["DV1"].IsObject) { throw new SerializationException(); }  DV1 = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["DV1"]);  }
        { if(!_buf["sign"].IsNumber) { throw new SerializationException(); }  Sign = (BoolSign)_buf["sign"].AsInt; }
        { if(!_buf["DV2"].IsObject) { throw new SerializationException(); }  DV2 = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["DV2"]);  }
    }

    public static Condition_DV检测 DeserializeCondition_DV检测(JSONNode _buf)
    {
        return new Condition_DV检测(_buf);
    }

    public readonly DynamicValue DV1;
    public readonly BoolSign Sign;
    public readonly DynamicValue DV2;
   
    public const int __ID__ = -1393272479;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        DV1?.ResolveRef(tables);
        DV2?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "DV1:" + DV1 + ","
        + "sign:" + Sign + ","
        + "DV2:" + DV2 + ","
        + "}";
    }
}
}

