
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum CustomerActionType
    {
        出现时 = 0,
        串完烤串后 = 1,
        订单完成后 = 2,
        离开时 = 3,
        其他顾客离开时 = 4,
    }

} 

