
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CustomerCGA : Luban.BeanBase
{
    public CustomerCGA(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (CustomerActionType)_buf["type"].AsInt; }
        { if(!_buf["cga"].IsObject) { throw new SerializationException(); }  Cga = global::cfg.CGA.DeserializeCGA(_buf["cga"]);  }
    }

    public static CustomerCGA DeserializeCustomerCGA(JSONNode _buf)
    {
        return new CustomerCGA(_buf);
    }

    public readonly CustomerActionType Type;
    public readonly CGA Cga;
   
    public const int __ID__ = -104220769;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Cga?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "cga:" + Cga + ","
        + "}";
    }
}
}

