
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DifficultyData : Luban.BeanBase
{
    public DifficultyData(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  Effects.Add(__v0); }   }
        { var __json0 = _buf["levelEffects"]; if(!__json0.IsArray) { throw new SerializationException(); } LevelEffects = new System.Collections.Generic.List<DifficultyEffectInLevel>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { DifficultyEffectInLevel __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.DifficultyEffectInLevel.DeserializeDifficultyEffectInLevel(__e0);  }  LevelEffects.Add(__v0); }   }
    }

    public static DifficultyData DeserializeDifficultyData(JSONNode _buf)
    {
        return new DifficultyData(_buf);
    }

    public readonly int Level;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<SustainEffect> Effects;
    public readonly System.Collections.Generic.List<DifficultyEffectInLevel> LevelEffects;
   
    public const int __ID__ = 1458229797;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
        foreach (var _e in LevelEffects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "levelEffects:" + Luban.StringUtil.CollectionToString(LevelEffects) + ","
        + "}";
    }
}
}

