
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Direction
    {
        无 = 0,
        上 = 1,
        下 = 2,
        左 = 3,
        右 = 4,
        上下文 = 5,
        随机 = 6,
    }

} 

