
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_串上某食材数量 : DynamicValue
{
    public DV_串上某食材数量(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["foodID"].IsString) { throw new SerializationException(); }  FoodID = _buf["foodID"]; }
    }

    public static DV_串上某食材数量 DeserializeDV_串上某食材数量(JSONNode _buf)
    {
        return new DV_串上某食材数量(_buf);
    }

    public readonly string FoodID;
   
    public const int __ID__ = -484722053;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "foodID:" + FoodID + ","
        + "}";
    }
}
}

