
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_当前串空位数 : DynamicValue
{
    public DV_当前串空位数(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Exp"].IsObject) { throw new SerializationException(); }  Exp = global::cfg.Expression.DeserializeExpression(_buf["Exp"]);  }
    }

    public static DV_当前串空位数 DeserializeDV_当前串空位数(JSONNode _buf)
    {
        return new DV_当前串空位数(_buf);
    }

    public readonly Expression Exp;
   
    public const int __ID__ = 1080925426;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Exp?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Exp:" + Exp + ","
        + "}";
    }
}
}

