
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_周围空位数 : DynamicValue
{
    public DV_周围空位数(JSONNode _buf)  : base(_buf) 
    {
    }

    public static DV_周围空位数 DeserializeDV_周围空位数(JSONNode _buf)
    {
        return new DV_周围空位数(_buf);
    }

   
    public const int __ID__ = -837767484;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

