
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_回文串 : DynamicValue
{
    public DV_回文串(JSONNode _buf)  : base(_buf) 
    {
    }

    public static DV_回文串 DeserializeDV_回文串(JSONNode _buf)
    {
        return new DV_回文串(_buf);
    }

   
    public const int __ID__ = 2051231676;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

