
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_周围食材数 : DynamicValue
{
    public DV_周围食材数(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static DV_周围食材数 DeserializeDV_周围食材数(JSONNode _buf)
    {
        return new DV_周围食材数(_buf);
    }

    public readonly string Id;
   
    public const int __ID__ = -830099386;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}
}

