
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public abstract partial class DynamicValue : Luban.BeanBase
{
    public DynamicValue(JSONNode _buf) 
    {
    }

    public static DynamicValue DeserializeDynamicValue(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "DV_周围食材数": return new DV_周围食材数(_buf);
            case "DV_值": return new DV_值(_buf);
            case "DV_周围空位数": return new DV_周围空位数(_buf);
            case "DV_当前构建烤串食材数量": return new DV_当前构建烤串食材数量(_buf);
            case "DV_食材实例数量": return new DV_食材实例数量(_buf);
            case "DV_售卖食材数量": return new DV_售卖食材数量(_buf);
            case "DV_回文串": return new DV_回文串(_buf);
            case "DV_串上某食材数量": return new DV_串上某食材数量(_buf);
            case "DV_当前串空位数": return new DV_当前串空位数(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

