
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EncounterData : Luban.BeanBase
{
    public EncounterData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (EncounterType)_buf["type"].AsInt; }
        { if(!_buf["num"].IsNumber) { throw new SerializationException(); }  Num = _buf["num"]; }
        { var __json0 = _buf["SEs"]; if(!__json0.IsArray) { throw new SerializationException(); } SEs = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  SEs.Add(__v0); }   }
    }

    public static EncounterData DeserializeEncounterData(JSONNode _buf)
    {
        return new EncounterData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly EncounterType Type;
    public readonly int Num;
    public readonly System.Collections.Generic.List<SustainEffect> SEs;
   
    public const int __ID__ = 688532317;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SEs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "type:" + Type + ","
        + "num:" + Num + ","
        + "SEs:" + Luban.StringUtil.CollectionToString(SEs) + ","
        + "}";
    }
}
}

