
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 其他实体GA类型
    /// </summary>
    public enum EntityGAType
    {
        被选中时 = 0,
        碰撞时 = 1,
        被碰撞时 = 2,
    }

} 

