
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EventType
    {
        无 = 0,
        每日开始系统前 = 1,
        每日开始系统后 = 2,
        完成烧烤后 = 3,
        抽牌后 = 4,
    }

} 

