
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Expression : Luban.BeanBase
{
    public Expression(JSONNode _buf) 
    {
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
    }

    public static Expression DeserializeExpression(JSONNode _buf)
    {
        return new Expression(_buf);
    }

    public readonly string Text;
   
    public const int __ID__ = 198012600;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "text:" + Text + ","
        + "}";
    }
}
}

