
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum FoodType
    {
        无 = 0,
        蔬菜 = 1,
        水果 = 2,
        肉类 = 4,
        海鲜 = 8,
        零食 = 16,
    }

} 

