
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 食材GA类型
    /// </summary>
    public enum FoodGAType
    {
        放上棋盘时 = 0,
        放上烤串前 = 1,
        放上烤串后 = 2,
        被选中时 = 3,
        碰撞时 = 4,
        被碰撞时 = 5,
    }

} 

