
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_使顾客离开 : GameAction
{
    public GA_使顾客离开(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetCustomerInfo.DeserializeGetCustomerInfo(_buf["info"]);  }
    }

    public static GA_使顾客离开 DeserializeGA_使顾客离开(JSONNode _buf)
    {
        return new GA_使顾客离开(_buf);
    }

    public readonly GetCustomerInfo Info;
   
    public const int __ID__ = -2030297373;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "}";
    }
}
}

