
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_修改稀有度概率 : GameAction
{
    public GA_修改稀有度概率(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["probs"].IsObject) { throw new SerializationException(); }  Probs = global::cfg.RankProbability.DeserializeRankProbability(_buf["probs"]);  }
    }

    public static GA_修改稀有度概率 DeserializeGA_修改稀有度概率(JSONNode _buf)
    {
        return new GA_修改稀有度概率(_buf);
    }

    public readonly RankProbability Probs;
   
    public const int __ID__ = -824728782;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Probs?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "probs:" + Probs + ","
        + "}";
    }
}
}

