
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_使食材获得GA : GameAction
{
    public GA_使食材获得GA(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetFoodInstancesInfo.DeserializeGetFoodInstancesInfo(_buf["info"]);  }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (FoodGAType)_buf["type"].AsInt; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  Actions.Add(__v0); }   }
    }

    public static GA_使食材获得GA DeserializeGA_使食材获得GA(JSONNode _buf)
    {
        return new GA_使食材获得GA(_buf);
    }

    public readonly GetFoodInstancesInfo Info;
    public readonly FoodGAType Type;
    public readonly string Description;
    public readonly System.Collections.Generic.List<GameAction> Actions;
   
    public const int __ID__ = 119058245;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "type:" + Type + ","
        + "description:" + Description + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

