
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_修改地块 : GameAction
{
    public GA_修改地块(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["tileId"].IsString) { throw new SerializationException(); }  TileId = _buf["tileId"]; }
    }

    public static GA_修改地块 DeserializeGA_修改地块(JSONNode _buf)
    {
        return new GA_修改地块(_buf);
    }

    public readonly string TileId;
   
    public const int __ID__ = 1172081335;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "tileId:" + TileId + ","
        + "}";
    }
}
}

