
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_减少Buff : GameAction
{
    public GA_减少Buff(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["buffID"].IsString) { throw new SerializationException(); }  BuffID = _buf["buffID"]; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
    }

    public static GA_减少Buff DeserializeGA_减少Buff(JSONNode _buf)
    {
        return new GA_减少Buff(_buf);
    }

    public readonly string BuffID;
    public readonly DynamicValue Value;
   
    public const int __ID__ = -874622310;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "buffID:" + BuffID + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

