
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_定点爆破 : GameAction
{
    public GA_定点爆破(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetCellInfo.DeserializeGetCellInfo(_buf["info"]);  }
    }

    public static GA_定点爆破 DeserializeGA_定点爆破(JSONNode _buf)
    {
        return new GA_定点爆破(_buf);
    }

    public readonly GetCellInfo Info;
   
    public const int __ID__ = 1264147410;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "}";
    }
}
}

