
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_创建实体 : GameAction
{
    public GA_创建实体(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["entityID"].IsString) { throw new SerializationException(); }  EntityID = _buf["entityID"]; }
    }

    public static GA_创建实体 DeserializeGA_创建实体(JSONNode _buf)
    {
        return new GA_创建实体(_buf);
    }

    public readonly string EntityID;
   
    public const int __ID__ = 1187171385;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "entityID:" + EntityID + ","
        + "}";
    }
}
}

