
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_效果选择 : GameAction
{
    public GA_效果选择(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["options"]; if(!__json0.IsArray) { throw new SerializationException(); } Options = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Options.Add(__v0); }   }
    }

    public static GA_效果选择 DeserializeGA_效果选择(JSONNode _buf)
    {
        return new GA_效果选择(_buf);
    }

    public readonly System.Collections.Generic.List<string> Options;
   
    public const int __ID__ = 1335960217;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

