
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 直接修改当前烧烤属性
/// </summary>
public sealed partial class GA_直接修改当前烧烤值 : GameAction
{
    public GA_直接修改当前烧烤值(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["rarityValue"].IsObject) { throw new SerializationException(); }  RarityValue = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["rarityValue"]);  }
        { if(!_buf["tasteValue"].IsObject) { throw new SerializationException(); }  TasteValue = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["tasteValue"]);  }
    }

    public static GA_直接修改当前烧烤值 DeserializeGA_直接修改当前烧烤值(JSONNode _buf)
    {
        return new GA_直接修改当前烧烤值(_buf);
    }

    /// <summary>
    /// 珍稀度修改
    /// </summary>
    public readonly DynamicValue RarityValue;
    /// <summary>
    /// 美味度修改
    /// </summary>
    public readonly DynamicValue TasteValue;
   
    public const int __ID__ = -672105020;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        RarityValue?.ResolveRef(tables);
        TasteValue?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "rarityValue:" + RarityValue + ","
        + "tasteValue:" + TasteValue + ","
        + "}";
    }
}
}

