
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_获得金币 : GameAction
{
    public GA_获得金币(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
    }

    public static GA_获得金币 DeserializeGA_获得金币(JSONNode _buf)
    {
        return new GA_获得金币(_buf);
    }

    public readonly DynamicValue Value;
   
    public const int __ID__ = 1566101845;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "}";
    }
}
}

