
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_触发遭遇 : GameAction
{
    public GA_触发遭遇(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
    }

    public static GA_触发遭遇 DeserializeGA_触发遭遇(JSONNode _buf)
    {
        return new GA_触发遭遇(_buf);
    }

    public readonly string ID;
   
    public const int __ID__ = 1610366378;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "}";
    }
}
}

