
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_随机触发 : GameAction
{
    public GA_随机触发(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  Actions.Add(__v0); }   }
    }

    public static GA_随机触发 DeserializeGA_随机触发(JSONNode _buf)
    {
        return new GA_随机触发(_buf);
    }

    public readonly System.Collections.Generic.List<GameAction> Actions;
   
    public const int __ID__ = 1711626939;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

