
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public abstract partial class GameAction : Luban.BeanBase
{
    public GameAction(JSONNode _buf) 
    {
    }

    public static GameAction DeserializeGameAction(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "GA_添加食材到烤串": return new GA_添加食材到烤串(_buf);
            case "GA_直接修改当前烧烤值": return new GA_直接修改当前烧烤值(_buf);
            case "GA_创建满意度乘区": return new GA_创建满意度乘区(_buf);
            case "GA_测试文字": return new GA_测试文字(_buf);
            case "GA_为食材加属性": return new GA_为食材加属性(_buf);
            case "GA_补充食材": return new GA_补充食材(_buf);
            case "GA_重复执行GA": return new GA_重复执行GA(_buf);
            case "GA_使食材获得GA": return new GA_使食材获得GA(_buf);
            case "GA_随机移动食材": return new GA_随机移动食材(_buf);
            case "GA_食材位移": return new GA_食材位移(_buf);
            case "GA_方向位移": return new GA_方向位移(_buf);
            case "GA_食材换位": return new GA_食材换位(_buf);
            case "GA_食材随机冲锋": return new GA_食材随机冲锋(_buf);
            case "GA_抽牌": return new GA_抽牌(_buf);
            case "GA_修改得分乘区": return new GA_修改得分乘区(_buf);
            case "GA_创建临时乘区": return new GA_创建临时乘区(_buf);
            case "GA_滑行": return new GA_滑行(_buf);
            case "GA_修改地块": return new GA_修改地块(_buf);
            case "GA_创建实体": return new GA_创建实体(_buf);
            case "GA_获得声望": return new GA_获得声望(_buf);
            case "GA_获得金币": return new GA_获得金币(_buf);
            case "GA_获得Buff": return new GA_获得Buff(_buf);
            case "GA_减少Buff": return new GA_减少Buff(_buf);
            case "GA_增加顾客等待值": return new GA_增加顾客等待值(_buf);
            case "GA_触发遭遇": return new GA_触发遭遇(_buf);
            case "GA_触发瞬时遭遇": return new GA_触发瞬时遭遇(_buf);
            case "GA_定点爆破": return new GA_定点爆破(_buf);
            case "GA_使顾客离开": return new GA_使顾客离开(_buf);
            case "GA_效果选择": return new GA_效果选择(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

