
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GetCustomerInfo : Luban.BeanBase
{
    public GetCustomerInfo(JSONNode _buf) 
    {
        { if(!_buf["strategy"].IsNumber) { throw new SerializationException(); }  Strategy = (GetCustomerStrategy)_buf["strategy"].AsInt; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
    }

    public static GetCustomerInfo DeserializeGetCustomerInfo(JSONNode _buf)
    {
        return new GetCustomerInfo(_buf);
    }

    public readonly GetCustomerStrategy Strategy;
    public readonly DynamicValue Value;
   
    public const int __ID__ = 1529512962;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "strategy:" + Strategy + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

