
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 网格形状数据
/// </summary>
public sealed partial class GridShapeData : Luban.BeanBase
{
    public GridShapeData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (GridShapeType)_buf["type"].AsInt; }
        { if(!_buf["pattern"].IsString) { throw new SerializationException(); }  Pattern = _buf["pattern"]; }
    }

    public static GridShapeData DeserializeGridShapeData(JSONNode _buf)
    {
        return new GridShapeData(_buf);
    }

    public readonly string ID;
    public readonly GridShapeType Type;
    public readonly string Pattern;
   
    public const int __ID__ = 665128485;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "type:" + Type + ","
        + "pattern:" + Pattern + ","
        + "}";
    }
}
}

