
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GuideTargetType
    {
        无 = 0,
        串签栏 = 1,
        待售串串 = 2,
        棋盘 = 3,
        简单对话 = 4,
    }

} 

