
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GuideStepDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, GuideStepData> _dataMap;
    private readonly System.Collections.Generic.List<GuideStepData> _dataList;
    
    public GuideStepDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, GuideStepData>(count);
        _dataList = new System.Collections.Generic.List<GuideStepData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GuideStepData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GuideStepData.DeserializeGuideStepData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.StepID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, GuideStepData> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideStepData> DataList => _dataList;

    public GuideStepData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideStepData Get(string key) => _dataMap[key];
    public GuideStepData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

