
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GuideStepData : Luban.BeanBase
{
    public GuideStepData(JSONNode _buf) 
    {
        { if(!_buf["stepID"].IsString) { throw new SerializationException(); }  StepID = _buf["stepID"]; }
        { if(!_buf["flowID"].IsString) { throw new SerializationException(); }  FlowID = _buf["flowID"]; }
        { if(!_buf["guideText"].IsString) { throw new SerializationException(); }  GuideText = _buf["guideText"]; }
        { if(!_buf["triggerAction"].IsNumber) { throw new SerializationException(); }  TriggerAction = (PlayerActionType)_buf["triggerAction"].AsInt; }
    }

    public static GuideStepData DeserializeGuideStepData(JSONNode _buf)
    {
        return new GuideStepData(_buf);
    }

    /// <summary>
    /// 教程步骤标识符
    /// </summary>
    public readonly string StepID;
    /// <summary>
    /// 流程标识符
    /// </summary>
    public readonly string FlowID;
    public readonly string GuideText;
    public readonly PlayerActionType TriggerAction;
   
    public const int __ID__ = 16594834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "stepID:" + StepID + ","
        + "flowID:" + FlowID + ","
        + "guideText:" + GuideText + ","
        + "triggerAction:" + TriggerAction + ","
        + "}";
    }
}
}

