
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class InstantEncounterDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, InstantEncounterData> _dataMap;
    private readonly System.Collections.Generic.List<InstantEncounterData> _dataList;
    
    public InstantEncounterDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, InstantEncounterData>(count);
        _dataList = new System.Collections.Generic.List<InstantEncounterData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            InstantEncounterData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.InstantEncounterData.DeserializeInstantEncounterData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, InstantEncounterData> DataMap => _dataMap;
    public System.Collections.Generic.List<InstantEncounterData> DataList => _dataList;

    public InstantEncounterData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public InstantEncounterData Get(string key) => _dataMap[key];
    public InstantEncounterData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

