
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MascotData : Luban.BeanBase
{
    public MascotData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["stackable"].IsBoolean) { throw new SerializationException(); }  Stackable = _buf["stackable"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = (Rank)_buf["rank"].AsInt; }
        { var __json0 = _buf["mainSE"]; if(!__json0.IsArray) { throw new SerializationException(); } MainSE = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  MainSE.Add(__v0); }   }
    }

    public static MascotData DeserializeMascotData(JSONNode _buf)
    {
        return new MascotData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly bool Stackable;
    public readonly Rank Rank;
    public readonly System.Collections.Generic.List<SustainEffect> MainSE;
   
    public const int __ID__ = -1960698061;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in MainSE) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "stackable:" + Stackable + ","
        + "rank:" + Rank + ","
        + "mainSE:" + Luban.StringUtil.CollectionToString(MainSE) + ","
        + "}";
    }
}
}

