
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MascotDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, MascotData> _dataMap;
    private readonly System.Collections.Generic.List<MascotData> _dataList;
    
    public MascotDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, MascotData>(count);
        _dataList = new System.Collections.Generic.List<MascotData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MascotData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MascotData.DeserializeMascotData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, MascotData> DataMap => _dataMap;
    public System.Collections.Generic.List<MascotData> DataList => _dataList;

    public MascotData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MascotData Get(string key) => _dataMap[key];
    public MascotData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

