
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Operatior
    {
        /// <summary>
        /// +
        /// </summary>
        加 = 0,
        /// <summary>
        /// -
        /// </summary>
        减 = 1,
        /// <summary>
        /// *
        /// </summary>
        乘 = 2,
        /// <summary>
        /// /
        /// </summary>
        除 = 3,
    }

} 

