
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class OptionDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, OptionData> _dataMap;
    private readonly System.Collections.Generic.List<OptionData> _dataList;
    
    public OptionDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, OptionData>(count);
        _dataList = new System.Collections.Generic.List<OptionData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            OptionData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.OptionData.DeserializeOptionData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, OptionData> DataMap => _dataMap;
    public System.Collections.Generic.List<OptionData> DataList => _dataList;

    public OptionData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public OptionData Get(string key) => _dataMap[key];
    public OptionData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

