
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class OptionData : Luban.BeanBase
{
    public OptionData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["effectDescription"].IsString) { throw new SerializationException(); }  EffectDescription = _buf["effectDescription"]; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<CGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CGA.DeserializeCGA(__e0);  }  Actions.Add(__v0); }   }
    }

    public static OptionData DeserializeOptionData(JSONNode _buf)
    {
        return new OptionData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly string EffectDescription;
    public readonly System.Collections.Generic.List<CGA> Actions;
   
    public const int __ID__ = -928414241;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "effectDescription:" + EffectDescription + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

