
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 玩家角色 - 数据层
/// </summary>
public sealed partial class PCData : Luban.BeanBase
{
    public PCData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["SkillDescription"].IsString) { throw new SerializationException(); }  SkillDescription = _buf["SkillDescription"]; }
        { var __json0 = _buf["SEs"]; if(!__json0.IsArray) { throw new SerializationException(); } SEs = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  SEs.Add(__v0); }   }
        { if(!_buf["Active"].IsString) { throw new SerializationException(); }  Active = _buf["Active"]; }
        { var __json0 = _buf["mascotList"]; if(!__json0.IsArray) { throw new SerializationException(); } MascotList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  MascotList.Add(__v0); }   }
        { var __json0 = _buf["stickList"]; if(!__json0.IsArray) { throw new SerializationException(); } StickList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  StickList.Add(__v0); }   }
    }

    public static PCData DeserializePCData(JSONNode _buf)
    {
        return new PCData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 角色描述
    /// </summary>
    public readonly string Description;
    public readonly string SkillDescription;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly System.Collections.Generic.List<SustainEffect> SEs;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly string Active;
    /// <summary>
    /// 初始吉祥物
    /// </summary>
    public readonly System.Collections.Generic.List<string> MascotList;
    /// <summary>
    /// 初始串
    /// </summary>
    public readonly System.Collections.Generic.List<string> StickList;
   
    public const int __ID__ = -1940636611;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SEs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "SkillDescription:" + SkillDescription + ","
        + "SEs:" + Luban.StringUtil.CollectionToString(SEs) + ","
        + "Active:" + Active + ","
        + "mascotList:" + Luban.StringUtil.CollectionToString(MascotList) + ","
        + "stickList:" + Luban.StringUtil.CollectionToString(StickList) + ","
        + "}";
    }
}
}

