
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Rank
    {
        默认 = 0,
        普通 = 1,
        稀有 = 2,
        史诗 = 3,
        传说 = 4,
    }

} 

