
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RankProbability : Luban.BeanBase
{
    public RankProbability(JSONNode _buf) 
    {
        { if(!_buf["probability_普通"].IsNumber) { throw new SerializationException(); }  Probability普通 = _buf["probability_普通"]; }
        { if(!_buf["probability_稀有"].IsNumber) { throw new SerializationException(); }  Probability稀有 = _buf["probability_稀有"]; }
        { if(!_buf["probability_史诗"].IsNumber) { throw new SerializationException(); }  Probability史诗 = _buf["probability_史诗"]; }
        { if(!_buf["probability_传说"].IsNumber) { throw new SerializationException(); }  Probability传说 = _buf["probability_传说"]; }
    }

    public static RankProbability DeserializeRankProbability(JSONNode _buf)
    {
        return new RankProbability(_buf);
    }

    public readonly float Probability普通;
    public readonly float Probability稀有;
    public readonly float Probability史诗;
    public readonly float Probability传说;
   
    public const int __ID__ = 660314185;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "probability普通:" + Probability普通 + ","
        + "probability稀有:" + Probability稀有 + ","
        + "probability史诗:" + Probability史诗 + ","
        + "probability传说:" + Probability传说 + ","
        + "}";
    }
}
}

