
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RecipeRule : Luban.BeanBase
{
    public RecipeRule(JSONNode _buf) 
    {
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { if(!_buf["action"].IsObject) { throw new SerializationException(); }  Action = global::cfg.CGA.DeserializeCGA(_buf["action"]);  }
    }

    public static RecipeRule DeserializeRecipeRule(JSONNode _buf)
    {
        return new RecipeRule(_buf);
    }

    public readonly int Rank;
    public readonly CGA Action;
   
    public const int __ID__ = 1641924042;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Action?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "rank:" + Rank + ","
        + "action:" + Action + ","
        + "}";
    }
}
}

