
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ReputationData : Luban.BeanBase
{
    public ReputationData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = _buf["rank"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Effects.Add(__v0); }   }
        { if(!_buf["totalReputation"].IsNumber) { throw new SerializationException(); }  TotalReputation = _buf["totalReputation"]; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<CGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CGA.DeserializeCGA(__e0);  }  Actions.Add(__v0); }   }
    }

    public static ReputationData DeserializeReputationData(JSONNode _buf)
    {
        return new ReputationData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly int Rank;
    public readonly string Description;
    public readonly System.Collections.Generic.List<string> Effects;
    public readonly int TotalReputation;
    public readonly System.Collections.Generic.List<CGA> Actions;
   
    public const int __ID__ = 1144950755;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "rank:" + Rank + ","
        + "description:" + Description + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "totalReputation:" + TotalReputation + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

