
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ReputationDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, ReputationData> _dataMap;
    private readonly System.Collections.Generic.List<ReputationData> _dataList;
    
    public ReputationDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, ReputationData>(count);
        _dataList = new System.Collections.Generic.List<ReputationData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ReputationData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ReputationData.DeserializeReputationData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ReputationData> DataMap => _dataMap;
    public System.Collections.Generic.List<ReputationData> DataList => _dataList;

    public ReputationData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ReputationData Get(string key) => _dataMap[key];
    public ReputationData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

