
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 烤串系统 - 数据层
/// </summary>
public sealed partial class StickData : Luban.BeanBase
{
    public StickData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["strategy"].IsNumber) { throw new SerializationException(); }  Strategy = (StickStrategy)_buf["strategy"].AsInt; }
        { if(!_buf["maxFoodCount"].IsNumber) { throw new SerializationException(); }  MaxFoodCount = _buf["maxFoodCount"]; }
        { if(!_buf["sprite"].IsString) { throw new SerializationException(); }  Sprite = _buf["sprite"]; }
    }

    public static StickData DeserializeStickData(JSONNode _buf)
    {
        return new StickData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 串签名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 串签描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 串签策略
    /// </summary>
    public readonly StickStrategy Strategy;
    public readonly int MaxFoodCount;
    /// <summary>
    /// 串签图
    /// </summary>
    public readonly string Sprite;
   
    public const int __ID__ = -2053465030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "strategy:" + Strategy + ","
        + "maxFoodCount:" + MaxFoodCount + ","
        + "sprite:" + Sprite + ","
        + "}";
    }
}
}

