
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TileDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, TileData> _dataMap;
    private readonly System.Collections.Generic.List<TileData> _dataList;
    
    public TileDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, TileData>(count);
        _dataList = new System.Collections.Generic.List<TileData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TileData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TileData.DeserializeTileData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, TileData> DataMap => _dataMap;
    public System.Collections.Generic.List<TileData> DataList => _dataList;

    public TileData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TileData Get(string key) => _dataMap[key];
    public TileData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

