
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TileData : Luban.BeanBase
{
    public TileData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["spriteName"].IsString) { throw new SerializationException(); }  SpriteName = _buf["spriteName"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["CGAs"]; if(!__json0.IsArray) { throw new SerializationException(); } CGAs = new System.Collections.Generic.List<TileCGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { TileCGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.TileCGA.DeserializeTileCGA(__e0);  }  CGAs.Add(__v0); }   }
    }

    public static TileData DeserializeTileData(JSONNode _buf)
    {
        return new TileData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 地块名称
    /// </summary>
    public readonly string Name;
    public readonly string SpriteName;
    /// <summary>
    /// 地块描述
    /// </summary>
    public readonly string Description;
    public readonly System.Collections.Generic.List<TileCGA> CGAs;
   
    public const int __ID__ = -2041834600;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in CGAs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "spriteName:" + SpriteName + ","
        + "description:" + Description + ","
        + "CGAs:" + Luban.StringUtil.CollectionToString(CGAs) + ","
        + "}";
    }
}
}

