
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BoolSign
    {
        /// <summary>
        /// &gt;
        /// </summary>
        大于 = 0,
        /// <summary>
        /// &lt;
        /// </summary>
        小于 = 1,
        /// <summary>
        /// &gt;=
        /// </summary>
        大于等于 = 2,
        /// <summary>
        /// &lt;=
        /// </summary>
        小于等于 = 3,
        /// <summary>
        /// ==
        /// </summary>
        等于 = 4,
        /// <summary>
        /// !=
        /// </summary>
        不等于 = 5,
    }

} 

