
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 卡牌检索信息
/// </summary>
public sealed partial class CardInfo : Luban.BeanBase
{
    public CardInfo(JSONNode _buf) 
    {
        { if(!_buf["amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["amount"]; }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = (Rank)_buf["rank"].AsInt; }
    }

    public static CardInfo DeserializeCardInfo(JSONNode _buf)
    {
        return new CardInfo(_buf);
    }

    public readonly int Amount;
    public readonly Rank Rank;
   
    public const int __ID__ = 56078334;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "amount:" + Amount + ","
        + "rank:" + Rank + ","
        + "}";
    }
}
}

