
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 卡牌系统 - 数据层
/// </summary>
public sealed partial class CardData : Luban.BeanBase
{
    public CardData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["cost"].IsNumber) { throw new SerializationException(); }  Cost = _buf["cost"]; }
        { if(!_buf["target"].IsNumber) { throw new SerializationException(); }  Target = (CardTargetType)_buf["target"].AsInt; }
        { var __json0 = _buf["CGAs"]; if(!__json0.IsArray) { throw new SerializationException(); } CGAs = new System.Collections.Generic.List<CardCGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CardCGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CardCGA.DeserializeCardCGA(__e0);  }  CGAs.Add(__v0); }   }
    }

    public static CardData DeserializeCardData(JSONNode _buf)
    {
        return new CardData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly int Cost;
    public readonly CardTargetType Target;
    public readonly System.Collections.Generic.List<CardCGA> CGAs;
   
    public const int __ID__ = 55917306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in CGAs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "cost:" + Cost + ","
        + "target:" + Target + ","
        + "CGAs:" + Luban.StringUtil.CollectionToString(CGAs) + ","
        + "}";
    }
}
}

