
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CGA : Luban.BeanBase
{
    public CGA(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["conditions"]; if(!__json0.IsArray) { throw new SerializationException(); } Conditions = new System.Collections.Generic.List<Condition>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Condition __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Condition.DeserializeCondition(__e0);  }  Conditions.Add(__v0); }   }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  Actions.Add(__v0); }   }
    }

    public static CGA DeserializeCGA(JSONNode _buf)
    {
        return new CGA(_buf);
    }

    /// <summary>
    /// 用于区分复杂CGA列表配置中的单个CGA
    /// </summary>
    public readonly string ID;
    public readonly System.Collections.Generic.List<Condition> Conditions;
    public readonly System.Collections.Generic.List<GameAction> Actions;
   
    public const int __ID__ = 66653;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Conditions) { _e?.ResolveRef(tables); }
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

