
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public abstract partial class Condition : Luban.BeanBase
{
    public Condition(JSONNode _buf) 
    {
    }

    public static Condition DeserializeCondition(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "Condition_DV检测": return new Condition_DV检测(_buf);
            case "Condition_当前交易烧烤食材数量": return new Condition_当前交易烧烤食材数量(_buf);
            case "Condition_食材周围空位": return new Condition_食材周围空位(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

