
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Condition_当前交易烧烤食材数量 : Condition
{
    public Condition_当前交易烧烤食材数量(JSONNode _buf)  : base(_buf) 
    {
    }

    public static Condition_当前交易烧烤食材数量 DeserializeCondition_当前交易烧烤食材数量(JSONNode _buf)
    {
        return new Condition_当前交易烧烤食材数量(_buf);
    }

   
    public const int __ID__ = -1880741734;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

