
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Condition_食材周围空位 : Condition
{
    public Condition_食材周围空位(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["sign"].IsNumber) { throw new SerializationException(); }  Sign = (BoolSign)_buf["sign"].AsInt; }
        { if(!_buf["amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["amount"]; }
    }

    public static Condition_食材周围空位 DeserializeCondition_食材周围空位(JSONNode _buf)
    {
        return new Condition_食材周围空位(_buf);
    }

    public readonly BoolSign Sign;
    public readonly int Amount;
   
    public const int __ID__ = 1274890804;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "sign:" + Sign + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

