
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CustomerTagDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, CustomerTagData> _dataMap;
    private readonly System.Collections.Generic.List<CustomerTagData> _dataList;
    
    public CustomerTagDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, CustomerTagData>(count);
        _dataList = new System.Collections.Generic.List<CustomerTagData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CustomerTagData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CustomerTagData.DeserializeCustomerTagData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CustomerTagData> DataMap => _dataMap;
    public System.Collections.Generic.List<CustomerTagData> DataList => _dataList;

    public CustomerTagData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CustomerTagData Get(string key) => _dataMap[key];
    public CustomerTagData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

