
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Dialogue : Luban.BeanBase
{
    public Dialogue(JSONNode _buf) 
    {
        { if(!_buf["speakerName"].IsString) { throw new SerializationException(); }  SpeakerName = _buf["speakerName"]; }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
    }

    public static Dialogue DeserializeDialogue(JSONNode _buf)
    {
        return new Dialogue(_buf);
    }

    public readonly string SpeakerName;
    public readonly string Content;
   
    public const int __ID__ = -169198088;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "speakerName:" + SpeakerName + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

