
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DifficultyEffectInLevel : Luban.BeanBase
{
    public DifficultyEffectInLevel(JSONNode _buf) 
    {
        { if(!_buf["LevelName"].IsString) { throw new SerializationException(); }  LevelName = _buf["LevelName"]; }
        { var __json0 = _buf["effectList"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectList = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  EffectList.Add(__v0); }   }
    }

    public static DifficultyEffectInLevel DeserializeDifficultyEffectInLevel(JSONNode _buf)
    {
        return new DifficultyEffectInLevel(_buf);
    }

    public readonly string LevelName;
    public readonly System.Collections.Generic.List<SustainEffect> EffectList;
   
    public const int __ID__ = 1570238067;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in EffectList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "LevelName:" + LevelName + ","
        + "effectList:" + Luban.StringUtil.CollectionToString(EffectList) + ","
        + "}";
    }
}
}

