
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class DifficultyDataTable
{
    private readonly System.Collections.Generic.Dictionary<int, DifficultyData> _dataMap;
    private readonly System.Collections.Generic.List<DifficultyData> _dataList;
    
    public DifficultyDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DifficultyData>(count);
        _dataList = new System.Collections.Generic.List<DifficultyData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DifficultyData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.DifficultyData.DeserializeDifficultyData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DifficultyData> DataMap => _dataMap;
    public System.Collections.Generic.List<DifficultyData> DataList => _dataList;

    public DifficultyData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DifficultyData Get(int key) => _dataMap[key];
    public DifficultyData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

