
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 构建阶段获取currentBBQ的动态值
/// </summary>
public sealed partial class DV_当前构建烤串食材数量 : DynamicValue
{
    public DV_当前构建烤串食材数量(JSONNode _buf)  : base(_buf) 
    {
    }

    public static DV_当前构建烤串食材数量 DeserializeDV_当前构建烤串食材数量(JSONNode _buf)
    {
        return new DV_当前构建烤串食材数量(_buf);
    }

   
    public const int __ID__ = -1093210149;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

