
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_值 : DynamicValue
{
    public DV_值(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
    }

    public static DV_值 DeserializeDV_值(JSONNode _buf)
    {
        return new DV_值(_buf);
    }

    public readonly int Number;
   
    public const int __ID__ = 2131919;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "number:" + Number + ","
        + "}";
    }
}
}

