
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DV_售卖食材数量 : DynamicValue
{
    public DV_售卖食材数量(JSONNode _buf)  : base(_buf) 
    {
    }

    public static DV_售卖食材数量 DeserializeDV_售卖食材数量(JSONNode _buf)
    {
        return new DV_售卖食材数量(_buf);
    }

   
    public const int __ID__ = 555184293;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

