
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EncounterDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, EncounterData> _dataMap;
    private readonly System.Collections.Generic.List<EncounterData> _dataList;
    
    public EncounterDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, EncounterData>(count);
        _dataList = new System.Collections.Generic.List<EncounterData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EncounterData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.EncounterData.DeserializeEncounterData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, EncounterData> DataMap => _dataMap;
    public System.Collections.Generic.List<EncounterData> DataList => _dataList;

    public EncounterData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EncounterData Get(string key) => _dataMap[key];
    public EncounterData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

