
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EntityDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, EntityData> _dataMap;
    private readonly System.Collections.Generic.List<EntityData> _dataList;
    
    public EntityDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, EntityData>(count);
        _dataList = new System.Collections.Generic.List<EntityData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EntityData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.EntityData.DeserializeEntityData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, EntityData> DataMap => _dataMap;
    public System.Collections.Generic.List<EntityData> DataList => _dataList;

    public EntityData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EntityData Get(string key) => _dataMap[key];
    public EntityData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

