
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EntityCGA : Luban.BeanBase
{
    public EntityCGA(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (EntityGAType)_buf["type"].AsInt; }
        { if(!_buf["action"].IsObject) { throw new SerializationException(); }  Action = global::cfg.CGA.DeserializeCGA(_buf["action"]);  }
    }

    public static EntityCGA DeserializeEntityCGA(JSONNode _buf)
    {
        return new EntityCGA(_buf);
    }

    public readonly EntityGAType Type;
    public readonly CGA Action;
   
    public const int __ID__ = 1263374714;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Action?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "action:" + Action + ","
        + "}";
    }
}
}

