
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum FoodInstanceState
    {
        无 = 0,
        棋盘上 = 1,
        被选中 = 2,
        烤串上 = 3,
    }

} 

