
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 食材系统 - 数据层
/// </summary>
public sealed partial class FoodData : Luban.BeanBase
{
    public FoodData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (FoodType)_buf["type"].AsInt; }
        { if(!_buf["tag"].IsNumber) { throw new SerializationException(); }  Tag = (FoodTag)_buf["tag"].AsInt; }
        { if(!_buf["rarity"].IsNumber) { throw new SerializationException(); }  Rarity = _buf["rarity"]; }
        { if(!_buf["taste"].IsNumber) { throw new SerializationException(); }  Taste = _buf["taste"]; }
        { if(!_buf["sprite"].IsString) { throw new SerializationException(); }  Sprite = _buf["sprite"]; }
        { if(!_buf["effectDescription"].IsString) { throw new SerializationException(); }  EffectDescription = _buf["effectDescription"]; }
        { var __json0 = _buf["CGAs"]; if(!__json0.IsArray) { throw new SerializationException(); } CGAs = new System.Collections.Generic.List<FoodCGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { FoodCGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.FoodCGA.DeserializeFoodCGA(__e0);  }  CGAs.Add(__v0); }   }
        { var __json0 = _buf["SEs"]; if(!__json0.IsArray) { throw new SerializationException(); } SEs = new System.Collections.Generic.List<SustainEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { SustainEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SustainEffect.DeserializeSustainEffect(__e0);  }  SEs.Add(__v0); }   }
        { if(!_buf["rank"].IsNumber) { throw new SerializationException(); }  Rank = (Rank)_buf["rank"].AsInt; }
    }

    public static FoodData DeserializeFoodData(JSONNode _buf)
    {
        return new FoodData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 食材名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 食材描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 食材类型
    /// </summary>
    public readonly FoodType Type;
    /// <summary>
    /// 食材标签
    /// </summary>
    public readonly FoodTag Tag;
    /// <summary>
    /// 珍稀值
    /// </summary>
    public readonly float Rarity;
    /// <summary>
    /// 美味值
    /// </summary>
    public readonly float Taste;
    /// <summary>
    /// 资源地址
    /// </summary>
    public readonly string Sprite;
    /// <summary>
    /// 效果描述
    /// </summary>
    public readonly string EffectDescription;
    /// <summary>
    /// 触发效果
    /// </summary>
    public readonly System.Collections.Generic.List<FoodCGA> CGAs;
    /// <summary>
    /// 持续效果
    /// </summary>
    public readonly System.Collections.Generic.List<SustainEffect> SEs;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly Rank Rank;
   
    public const int __ID__ = 443643208;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in CGAs) { _e?.ResolveRef(tables); }
        foreach (var _e in SEs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "type:" + Type + ","
        + "tag:" + Tag + ","
        + "rarity:" + Rarity + ","
        + "taste:" + Taste + ","
        + "sprite:" + Sprite + ","
        + "effectDescription:" + EffectDescription + ","
        + "CGAs:" + Luban.StringUtil.CollectionToString(CGAs) + ","
        + "SEs:" + Luban.StringUtil.CollectionToString(SEs) + ","
        + "rank:" + Rank + ","
        + "}";
    }
}
}

