
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_为食材加属性 : GameAction
{
    public GA_为食材加属性(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["rarity"].IsObject) { throw new SerializationException(); }  Rarity = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["rarity"]);  }
        { if(!_buf["taste"].IsObject) { throw new SerializationException(); }  Taste = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["taste"]);  }
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetFoodInstancesInfo.DeserializeGetFoodInstancesInfo(_buf["info"]);  }
    }

    public static GA_为食材加属性 DeserializeGA_为食材加属性(JSONNode _buf)
    {
        return new GA_为食材加属性(_buf);
    }

    public readonly DynamicValue Rarity;
    public readonly DynamicValue Taste;
    public readonly GetFoodInstancesInfo Info;
   
    public const int __ID__ = 939791171;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Rarity?.ResolveRef(tables);
        Taste?.ResolveRef(tables);
        Info?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "rarity:" + Rarity + ","
        + "taste:" + Taste + ","
        + "info:" + Info + ","
        + "}";
    }
}
}

