
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 事件效果
/// </summary>
public sealed partial class GA_修改得分乘区 : GameAction
{
    public GA_修改得分乘区(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
        { if(!_buf["sender"].IsString) { throw new SerializationException(); }  Sender = _buf["sender"]; }
        { if(!_buf["isAdd"].IsBoolean) { throw new SerializationException(); }  IsAdd = _buf["isAdd"]; }
    }

    public static GA_修改得分乘区 DeserializeGA_修改得分乘区(JSONNode _buf)
    {
        return new GA_修改得分乘区(_buf);
    }

    public readonly float Value;
    public readonly string Sender;
    public readonly bool IsAdd;
   
    public const int __ID__ = 1152146945;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "sender:" + Sender + ","
        + "isAdd:" + IsAdd + ","
        + "}";
    }
}
}

