
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_创建满意度乘区 : GameAction
{
    public GA_创建满意度乘区(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static GA_创建满意度乘区 DeserializeGA_创建满意度乘区(JSONNode _buf)
    {
        return new GA_创建满意度乘区(_buf);
    }

    /// <summary>
    /// 乘区名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -1614858058;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

