
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_方向位移 : GameAction
{
    public GA_方向位移(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetFoodInstancesInfo.DeserializeGetFoodInstancesInfo(_buf["info"]);  }
        { if(!_buf["dir"].IsNumber) { throw new SerializationException(); }  Dir = (Direction)_buf["dir"].AsInt; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
    }

    public static GA_方向位移 DeserializeGA_方向位移(JSONNode _buf)
    {
        return new GA_方向位移(_buf);
    }

    public readonly GetFoodInstancesInfo Info;
    public readonly Direction Dir;
    public readonly DynamicValue Value;
   
    public const int __ID__ = 1334010891;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "dir:" + Dir + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

