
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_测试文字 : GameAction
{
    public GA_测试文字(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
    }

    public static GA_测试文字 DeserializeGA_测试文字(JSONNode _buf)
    {
        return new GA_测试文字(_buf);
    }

    /// <summary>
    /// 输出文本
    /// </summary>
    public readonly string Text;
   
    public const int __ID__ = 1405633631;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "text:" + Text + ","
        + "}";
    }
}
}

