
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_添加食材到烤串 : GameAction
{
    public GA_添加食材到烤串(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetFoodInstancesInfo.DeserializeGetFoodInstancesInfo(_buf["info"]);  }
    }

    public static GA_添加食材到烤串 DeserializeGA_添加食材到烤串(JSONNode _buf)
    {
        return new GA_添加食材到烤串(_buf);
    }

    public readonly GetFoodInstancesInfo Info;
   
    public const int __ID__ = 1881371843;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "}";
    }
}
}

