
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_重复执行GA : GameAction
{
    public GA_重复执行GA(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
        { if(!_buf["action"].IsObject) { throw new SerializationException(); }  Action = global::cfg.GameAction.DeserializeGameAction(_buf["action"]);  }
    }

    public static GA_重复执行GA DeserializeGA_重复执行GA(JSONNode _buf)
    {
        return new GA_重复执行GA(_buf);
    }

    public readonly DynamicValue Value;
    public readonly GameAction Action;
   
    public const int __ID__ = 45652548;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Value?.ResolveRef(tables);
        Action?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "action:" + Action + ","
        + "}";
    }
}
}

