
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GA_食材位移 : GameAction
{
    public GA_食材位移(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["info"].IsObject) { throw new SerializationException(); }  Info = global::cfg.GetFoodInstancesInfo.DeserializeGetFoodInstancesInfo(_buf["info"]);  }
        { if(!_buf["cellInfo"].IsObject) { throw new SerializationException(); }  CellInfo = global::cfg.GetCellInfo.DeserializeGetCellInfo(_buf["cellInfo"]);  }
    }

    public static GA_食材位移 DeserializeGA_食材位移(JSONNode _buf)
    {
        return new GA_食材位移(_buf);
    }

    public readonly GetFoodInstancesInfo Info;
    public readonly GetCellInfo CellInfo;
   
    public const int __ID__ = 1728829092;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Info?.ResolveRef(tables);
        CellInfo?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "info:" + Info + ","
        + "cellInfo:" + CellInfo + ","
        + "}";
    }
}
}

