
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GetFoodInstanceStrategy
    {
        随机 = 0,
        周围随机 = 1,
        九宫格随机 = 2,
        自己 = 3,
        选取 = 4,
    }

} 

