
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GetFoodInstancesInfo : Luban.BeanBase
{
    public GetFoodInstancesInfo(JSONNode _buf) 
    {
        { if(!_buf["strategy"].IsNumber) { throw new SerializationException(); }  Strategy = (GetFoodInstanceStrategy)_buf["strategy"].AsInt; }
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
        { var __json0 = _buf["types"]; if(!__json0.IsArray) { throw new SerializationException(); } Types = new System.Collections.Generic.List<FoodInstanceState>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { FoodInstanceState __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (FoodInstanceState)__e0.AsInt; }  Types.Add(__v0); }   }
    }

    public static GetFoodInstancesInfo DeserializeGetFoodInstancesInfo(JSONNode _buf)
    {
        return new GetFoodInstancesInfo(_buf);
    }

    public readonly GetFoodInstanceStrategy Strategy;
    public readonly DynamicValue Value;
    public readonly System.Collections.Generic.List<FoodInstanceState> Types;
   
    public const int __ID__ = 1609289720;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "strategy:" + Strategy + ","
        + "value:" + Value + ","
        + "types:" + Luban.StringUtil.CollectionToString(Types) + ","
        + "}";
    }
}
}

