
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class InstantEncounterData : Luban.BeanBase
{
    public InstantEncounterData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["options"]; if(!__json0.IsArray) { throw new SerializationException(); } Options = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Options.Add(__v0); }   }
    }

    public static InstantEncounterData DeserializeInstantEncounterData(JSONNode _buf)
    {
        return new InstantEncounterData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly System.Collections.Generic.List<string> Options;
   
    public const int __ID__ = -588017860;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

