
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LevelDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, LevelData> _dataMap;
    private readonly System.Collections.Generic.List<LevelData> _dataList;
    
    public LevelDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, LevelData>(count);
        _dataList = new System.Collections.Generic.List<LevelData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.LevelData.DeserializeLevelData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LevelData> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelData> DataList => _dataList;

    public LevelData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelData Get(string key) => _dataMap[key];
    public LevelData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

