
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class OptionData : Luban.BeanBase
{
    public OptionData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["effectDescription"].IsString) { throw new SerializationException(); }  EffectDescription = _buf["effectDescription"]; }
        { if(!_buf["action"].IsObject) { throw new SerializationException(); }  Action = global::cfg.CGA.DeserializeCGA(_buf["action"]);  }
    }

    public static OptionData DeserializeOptionData(JSONNode _buf)
    {
        return new OptionData(_buf);
    }

    public readonly string ID;
    public readonly string Name;
    public readonly string Description;
    public readonly string EffectDescription;
    public readonly CGA Action;
   
    public const int __ID__ = -928414241;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Action?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "effectDescription:" + EffectDescription + ","
        + "action:" + Action + ","
        + "}";
    }
}
}

