
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PCDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, PCData> _dataMap;
    private readonly System.Collections.Generic.List<PCData> _dataList;
    
    public PCDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, PCData>(count);
        _dataList = new System.Collections.Generic.List<PCData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PCData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PCData.DeserializePCData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, PCData> DataMap => _dataMap;
    public System.Collections.Generic.List<PCData> DataList => _dataList;

    public PCData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PCData Get(string key) => _dataMap[key];
    public PCData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

