
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Rank
    {
        /// <summary>
        /// 无
        /// </summary>
        默认 = 0,
        /// <summary>
        /// 常见
        /// </summary>
        普通 = 1,
        /// <summary>
        /// 不赖
        /// </summary>
        稀有 = 2,
        /// <summary>
        /// 稀世
        /// </summary>
        史诗 = 3,
        /// <summary>
        /// 传奇
        /// </summary>
        传说 = 4,
    }

} 

