
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RecipeRule_食材共存 : RecipeRule
{
    public RecipeRule_食材共存(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["FoodIds"]; if(!__json0.IsArray) { throw new SerializationException(); } FoodIds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  FoodIds.Add(__v0); }   }
    }

    public static RecipeRule_食材共存 DeserializeRecipeRule_食材共存(JSONNode _buf)
    {
        return new RecipeRule_食材共存(_buf);
    }

    public readonly System.Collections.Generic.List<string> FoodIds;
   
    public const int __ID__ = 267309933;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "FoodIds:" + Luban.StringUtil.CollectionToString(FoodIds) + ","
        + "}";
    }
}
}

