
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RecipeData : Luban.BeanBase
{
    public RecipeData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["ruleDescription"].IsString) { throw new SerializationException(); }  RuleDescription = _buf["ruleDescription"]; }
        { if(!_buf["actionDescription"].IsString) { throw new SerializationException(); }  ActionDescription = _buf["actionDescription"]; }
        { var __json0 = _buf["rules"]; if(!__json0.IsArray) { throw new SerializationException(); } Rules = new System.Collections.Generic.List<RecipeRule>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { RecipeRule __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.RecipeRule.DeserializeRecipeRule(__e0);  }  Rules.Add(__v0); }   }
        { var __json0 = _buf["GA"]; if(!__json0.IsArray) { throw new SerializationException(); } GA = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  GA.Add(__v0); }   }
    }

    public static RecipeData DeserializeRecipeData(JSONNode _buf)
    {
        return new RecipeData(_buf);
    }

    /// <summary>
    /// 配方唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 配方名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 配方描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 规则描述
    /// </summary>
    public readonly string RuleDescription;
    /// <summary>
    /// 效果描述
    /// </summary>
    public readonly string ActionDescription;
    /// <summary>
    /// 配方规则列表，Match依据
    /// </summary>
    public readonly System.Collections.Generic.List<RecipeRule> Rules;
    /// <summary>
    /// GAList
    /// </summary>
    public readonly System.Collections.Generic.List<GameAction> GA;
   
    public const int __ID__ = 1641487992;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rules) { _e?.ResolveRef(tables); }
        foreach (var _e in GA) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "ruleDescription:" + RuleDescription + ","
        + "actionDescription:" + ActionDescription + ","
        + "rules:" + Luban.StringUtil.CollectionToString(Rules) + ","
        + "GA:" + Luban.StringUtil.CollectionToString(GA) + ","
        + "}";
    }
}
}

