
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 配方规则，通过才能执行
/// </summary>
public abstract partial class RecipeRule : Luban.BeanBase
{
    public RecipeRule(JSONNode _buf) 
    {
    }

    public static RecipeRule DeserializeRecipeRule(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "RecipeRule_食材共存": return new RecipeRule_食材共存(_buf);
            case "RecipeRule_类型共存": return new RecipeRule_类型共存(_buf);
            case "RecipeRule_动态值": return new RecipeRule_动态值(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

