
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RecipeRule_类型共存 : RecipeRule
{
    public RecipeRule_类型共存(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["types"]; if(!__json0.IsArray) { throw new SerializationException(); } Types = new System.Collections.Generic.List<FoodType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { FoodType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (FoodType)__e0.AsInt; }  Types.Add(__v0); }   }
    }

    public static RecipeRule_类型共存 DeserializeRecipeRule_类型共存(JSONNode _buf)
    {
        return new RecipeRule_类型共存(_buf);
    }

    public readonly System.Collections.Generic.List<FoodType> Types;
   
    public const int __ID__ = 46909388;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "types:" + Luban.StringUtil.CollectionToString(Types) + ","
        + "}";
    }
}
}

