
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SE_基于线性GA : SustainEffect
{
    public SE_基于线性GA(JSONNode _buf)  : base(_buf) 
    {
        { var __json0 = _buf["onAddAction"]; if(!__json0.IsArray) { throw new SerializationException(); } OnAddAction = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  OnAddAction.Add(__v0); }   }
        { var __json0 = _buf["onRemoveAction"]; if(!__json0.IsArray) { throw new SerializationException(); } OnRemoveAction = new System.Collections.Generic.List<GameAction>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { GameAction __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.GameAction.DeserializeGameAction(__e0);  }  OnRemoveAction.Add(__v0); }   }
    }

    public static SE_基于线性GA DeserializeSE_基于线性GA(JSONNode _buf)
    {
        return new SE_基于线性GA(_buf);
    }

    /// <summary>
    /// 动作列表
    /// </summary>
    public readonly System.Collections.Generic.List<GameAction> OnAddAction;
    /// <summary>
    /// 动作列表
    /// </summary>
    public readonly System.Collections.Generic.List<GameAction> OnRemoveAction;
   
    public const int __ID__ = 1636535939;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        foreach (var _e in OnAddAction) { _e?.ResolveRef(tables); }
        foreach (var _e in OnRemoveAction) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "onAddAction:" + Luban.StringUtil.CollectionToString(OnAddAction) + ","
        + "onRemoveAction:" + Luban.StringUtil.CollectionToString(OnRemoveAction) + ","
        + "}";
    }
}
}

