
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SE_监听事件 : SustainEffect
{
    public SE_监听事件(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["evt"].IsNumber) { throw new SerializationException(); }  Evt = (EventType)_buf["evt"].AsInt; }
        { var __json0 = _buf["actions"]; if(!__json0.IsArray) { throw new SerializationException(); } Actions = new System.Collections.Generic.List<CGA>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CGA __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CGA.DeserializeCGA(__e0);  }  Actions.Add(__v0); }   }
    }

    public static SE_监听事件 DeserializeSE_监听事件(JSONNode _buf)
    {
        return new SE_监听事件(_buf);
    }

    public readonly EventType Evt;
    /// <summary>
    /// 动作列表
    /// </summary>
    public readonly System.Collections.Generic.List<CGA> Actions;
   
    public const int __ID__ = -655955885;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "evt:" + Evt + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "}";
    }
}
}

