
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class StickDataTable
{
    private readonly System.Collections.Generic.Dictionary<string, StickData> _dataMap;
    private readonly System.Collections.Generic.List<StickData> _dataList;
    
    public StickDataTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, StickData>(count);
        _dataList = new System.Collections.Generic.List<StickData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StickData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.StickData.DeserializeStickData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, StickData> DataMap => _dataMap;
    public System.Collections.Generic.List<StickData> DataList => _dataList;

    public StickData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StickData Get(string key) => _dataMap[key];
    public StickData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

