
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public FoodDataTable FoodDataTable {get; }
    public StickDataTable StickDataTable {get; }
    public CustomerTagDataTable CustomerTagDataTable {get; }
    public RecipeDataTable RecipeDataTable {get; }
    public MascotDataTable MascotDataTable {get; }
    public PCDataTable PCDataTable {get; }
    public CardDataTable CardDataTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        FoodDataTable = new FoodDataTable(loader("fooddatatable"));
        StickDataTable = new StickDataTable(loader("stickdatatable"));
        CustomerTagDataTable = new CustomerTagDataTable(loader("customertagdatatable"));
        RecipeDataTable = new RecipeDataTable(loader("recipedatatable"));
        MascotDataTable = new MascotDataTable(loader("mascotdatatable"));
        PCDataTable = new PCDataTable(loader("pcdatatable"));
        CardDataTable = new CardDataTable(loader("carddatatable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        FoodDataTable.ResolveRef(this);
        StickDataTable.ResolveRef(this);
        CustomerTagDataTable.ResolveRef(this);
        RecipeDataTable.ResolveRef(this);
        MascotDataTable.ResolveRef(this);
        PCDataTable.ResolveRef(this);
        CardDataTable.ResolveRef(this);
    }
}

}
