
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TagCGA : Luban.BeanBase
{
    public TagCGA(JSONNode _buf) 
    {
        { if(!_buf["GADescription"].IsString) { throw new SerializationException(); }  GADescription = _buf["GADescription"]; }
        { if(!_buf["CDDescription"].IsString) { throw new SerializationException(); }  CDDescription = _buf["CDDescription"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (CustomerTagType)_buf["type"].AsInt; }
        { if(!_buf["cga"].IsObject) { throw new SerializationException(); }  Cga = global::cfg.CGA.DeserializeCGA(_buf["cga"]);  }
    }

    public static TagCGA DeserializeTagCGA(JSONNode _buf)
    {
        return new TagCGA(_buf);
    }

    public readonly string GADescription;
    public readonly string CDDescription;
    public readonly CustomerTagType Type;
    public readonly CGA Cga;
   
    public const int __ID__ = -1797401949;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Cga?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "GADescription:" + GADescription + ","
        + "CDDescription:" + CDDescription + ","
        + "type:" + Type + ","
        + "cga:" + Cga + ","
        + "}";
    }
}
}

