
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TileData : Luban.BeanBase
{
    public TileData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
    }

    public static TileData DeserializeTileData(JSONNode _buf)
    {
        return new TileData(_buf);
    }

    /// <summary>
    /// 唯一标识符
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 地块名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 地块描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -2041834600;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

