
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 地块效果类型
    /// </summary>
    public enum TileEffectType
    {
        实体被放置 = 0,
        实体移动进入 = 1,
    }

} 

